FROM fedora:23
MAINTAINER Kazuhisa Hara <kazuhisya@gmail.com>

RUN dnf install -y dnf-plugins-core rpmdevtools make git
COPY / /yrmcds-rpm
WORKDIR /yrmcds-rpm

RUN dnf builddep -y ./yrmcds.spec
RUN make rpm
RUN dnf install -y \
        --nogpgcheck \
        ./dist/RPMS/x86_64/yrmcds-[^d.+].* \
        copr-cli
RUN /usr/bin/install -o nobody -g nobody -m 0700 -d /var/tmp/yrmcds && /bin/rm -f /var/tmp/yrmcds/*

EXPOSE 11211

CMD ["-f", "/etc/yrmcds/yrmcds.conf"]
ENTRYPOINT ["/usr/sbin/yrmcdsd"]
